/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progress_bar;

import progress_bar.*;
import java.util.Random;

/**
 *
 * @author User
 */
public class pilihan_bahasa extends javax.swing.JFrame {
    private int skorjava = 0;
    private int skorphp = 0;
   
    /**
     * Creates new form bahasafavorit
     */
    public pilihan_bahasa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeljudul1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labeljava = new javax.swing.JLabel();
        labelsukajava = new javax.swing.JLabel();
        btnjava = new javax.swing.JButton();
        labelphp = new javax.swing.JLabel();
        labelsukaphp = new javax.swing.JLabel();
        btnphp = new javax.swing.JButton();
        persenjavaphp = new javax.swing.JProgressBar();
        btnreset = new javax.swing.JButton();
        labeljudul = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeljudul1.setFont(new java.awt.Font("Bodoni Bd BT", 0, 30)); // NOI18N
        labeljudul1.setText("Silahkan Pilih Bahasa");
        getContentPane().add(labeljudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 300, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        labeljava.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        labeljava.setText("Java");

        labelsukajava.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        labelsukajava.setText("0");

        btnjava.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnjava.setText("Vote");
        btnjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjavaActionPerformed(evt);
            }
        });

        labelphp.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        labelphp.setText("PHP");

        labelsukaphp.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        labelsukaphp.setText("0");

        btnphp.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnphp.setText("Vote");
        btnphp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphpActionPerformed(evt);
            }
        });

        persenjavaphp.setBackground(new java.awt.Color(0, 255, 0));
        persenjavaphp.setForeground(new java.awt.Color(0, 0, 0));
        persenjavaphp.setStringPainted(true);

        btnreset.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        labeljudul.setFont(new java.awt.Font("Bodoni Bd BT", 0, 30)); // NOI18N
        labeljudul.setText("Favorit Kamu");

        jLabel3.setFont(new java.awt.Font("Trajan Pro 3", 1, 36)); // NOI18N
        jLabel3.setText("Terima Kasih");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelphp)
                    .addComponent(labeljava))
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelsukajava)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(btnjava))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelsukaphp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnphp)))
                        .addGap(100, 100, 100))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnreset)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(persenjavaphp, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(labeljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(labeljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnjava)
                            .addComponent(labelsukajava)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labeljava)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelsukaphp)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelphp))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnphp)))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persenjavaphp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjavaActionPerformed
       for (int counter =1; counter<=1; counter++){                      
                skorjava = ++skorjava;   
        }
    labelsukajava.setText(String.valueOf(skorjava));
    persenjavaphp.setValue(skorjava);
    persenjavaphp.setMaximum(skorjava+skorphp);
    }//GEN-LAST:event_btnjavaActionPerformed

    private void btnphpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphpActionPerformed
        for (int counter =1; counter<=1; counter++){                      
                skorphp = ++skorphp;   
        }
    labelsukaphp.setText(String.valueOf(skorphp));
    persenjavaphp.setValue(skorjava);
    persenjavaphp.setMaximum(skorjava+skorphp);
    }//GEN-LAST:event_btnphpActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
       skorjava=0;
       skorphp=0;
       labelsukaphp.setText(String.valueOf(skorphp));
       labelsukajava.setText(String.valueOf(skorjava));
       persenjavaphp.setMaximum(100);
       persenjavaphp.setValue(0);
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihan_bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihan_bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihan_bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihan_bahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihan_bahasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjava;
    private javax.swing.JButton btnphp;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labeljava;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labeljudul1;
    private javax.swing.JLabel labelphp;
    private javax.swing.JLabel labelsukajava;
    private javax.swing.JLabel labelsukaphp;
    private javax.swing.JProgressBar persenjavaphp;
    // End of variables declaration//GEN-END:variables
}
